**Welcome**

Welcome to your guided first steps on Python. 

A researcher in a lab working with social data may encounter similar challenges to the ones we will be introducing to you today.

First, we will have a look at the Jupyter Notebook and its parts. 
We will then learn to define about variables and how to perform calculations with them. 
Lastly we will learn about functions and methods in Python. 

Please follow along by running the code on your own notebook.


Learning Objectives:

*   Looking at Python: Familiarize yourself with the Jupyter notebook
*   Labeling your Data: Define variables and their types
*   Touching your Data: Run basic calculations

# Jupyter Notebooks

A Jupyter notebook is an app. 

It provides a web-based interactive computing platform where we can use code, narrative text, equations and visualizations. It will allow us to practice python programming. 

In it, you will see this cell or box:

This is where we will write both code and text. 

When we write code in it, we can run it by clicking the run button on the left that looks like a play button. The button will show when you run your mouse over it.

*print(3+5)*

In [ ]:
print(3+5)

8

Another way to run the code on your box is with the keyboard shortcut *Shift + Enter*

In [ ]:
print(2+2)

4

If put your cursor in between boxes, it will allow you to add a new box for either text or code.

Let's input some text in our boxes and style it.

# Text and Font

In a text cell the symbol # will enlarge the text, turning it into a header. 

Try by adding a text box below this and typing:

Hello

*#Hello*

Hello
#Hello

In a code cell, the symbol # will turn the code into text. This is referred to as a comment. The program will never try to execute a comment, it is text meant to describe the code for the human reader.

Try it by runnning the code cell below:

In [1]:
print(3+5) #This code will print out the answer to the sum.
#print(3+5)

8

What do you think will happen if we input random text into a code cell?

In [2]:
addition

NameError: ignored

The code cell above contains an error, as the word addition is not correct code. This is how Jupyter notebooks lets you know there is an error in your code.

# Variables and Statements

Now that we have typed in some text, let's input instead some code.

We will first learn to create variables. 

A Python variable is a memory space used to store values.

You can think of this memory space as a container. The container is assigned a name, and inside of it, it contains a specific value, such as a letter or a number.

A value is the fundamental thing (a letter, a number, a sign or a combination of these) that the program manipulates. 

We will use the operator "=" to "store" the value 1 in a variable Response_ID
Like so:

In [7]:
Response_ID=1

From now on, in any code we write, our notebook will remember the value assigned to the variable *Response_ID*. Variable names can be any combinations of letters, numbers and underscores.

Naming variables and using the function *print* will be enough for us to program the writing of a first simple sentence.  

For example, if I create variables for a participant's identifier and their age, then I can recall these values into a sentence that uses them.

The rest of the text in my sentence, I can include by separating it from the variables with commas and enclosing it in quotation marks. Like so:

In [2]:
age_1= 34
Response_ID = 1
print('Participant', Response_ID, 'is', age_1, 'years old.')

Participant 1 is 34 years old.

Try setting a variable for your name and one for the city where you were born. Then have the notebook print out a sentence saying where you were born.

In [7]:
name='sam'

# Types of Variables

According to the kind of values that make them up, variables can be of different types.

This is important because different kinds of variables will be subject to different rules and operations.

What kind of variables can you think of?

The first type of variables we will look at are those made of **integers** and we will call them *(int)*

An integer is a number that we can count. A whole number. Say, 3. Or 345. Intergers allow us to count the number of whole things we have. 

Fractions (or numbers with decimals) instead are called **floating numbers** *(float)*

A floating number is a fractional number and it allows us to measure the dimension of something. For example, my thumb is 59.32 mm long.

Lastly, we have variables made of letters or text and symbols, and we call those string variables or **strings** *(str)*

So what kind of variable was the one you created for your name?

Use the function *type* to have the notebook tell you what type of variable it is.

In [8]:
type(name)

str

The function *type* can also be used with values rather than variable names:

In [9]:
type(52)

int

# Calculations with Variables

How can we have the notebook print how old Participant 1 will be in three years?

We already have a variable for their age. So we can create a new one for their age in three years and have it print out.

In [5]:
Later_Age_1 = age_1 + 3
print(Later_Age_1)

37

This has added an *int variable* with an *int value*.

To multiply we will the asterix symbol *

In [13]:
b=3*3
print(b)

9

This has multiplied two *int values*.

To divide we will use the slash symbol /.

In [14]:
c=5/2
print(c)

2.5

In this case we divided two *int* values and obtained a *float* one

Let's square a number.

In [15]:
d=3**2
print(d)

9

Many operations are valid for string values and variables too.

By "adding them" with a '+' we can concatenate them, like blocks into sentences.

I can create a variable made of two string values for my full name. I make sure to separate the string values with quotation marks:

In [16]:
Hometown = 'Saint'+'Louis'

print(Hometown)

SaintLouis

As you can see, the two words have been assembled one next to the other.

I may want to add a space here. What kind of value is a space and how can you add it?

In [17]:
type(' ')

str

In [18]:
Hometown = 'Saint'+' '+'Louis'
print(Hometown)

Saint Louis

Numbers written in between ' ' will show as string variables instead of integers variables.

In [19]:
print('Participat', Response_ID, 'is', '34')

Participat 1 is 34

What would happen if I want to add a string value to an integer value?

In [4]:
e='participant'+1
print(e)

TypeError: ignored

The code cell above holds a mistake because variables of different types cannot be added.

# Operations Mixing Variable Types

Python has a trick that will allows us to use different variable types in one same operation: casting.

Casting a variable is converting it to another type. To convert it, we will type first the type we want the variable to have, and right after, we type in a parenthesis the variable. For example: *str(1)*.

We saw before that writing a number between quotation marks will show it as a string value. If  that is true, then adding two numbers in quotations would concatenate them:

In [21]:
print('1' + '2')

12

How could I convert (cast) this string ('2') into an integer to use it in a sum?

In [22]:
print(1 + int('2'))

3

We can also cast an int value into a string:

In [23]:
print(str(1) + '2')

12

Great. Questions so far?

#Functions

Learning Objectives:

*   Creating pre-established processes for your data: Understand the concept of a function and syntaxis of a function
*   Manipulating your Daeta: View examples of methods

A function is like a button, that when pressed (called) will do an action to a variable. 

When we created a variable, we taught the program what value to recall when we write the variable name.

When we create a function, we teach the program what action to recall when we write the function name. Not only to recall it, but also to perform this action on a specific variable.

In [27]:
def summarize(who):
    print("Participant " + str(who) + " " + "is " + str(age_1) + " years old, and will be " + str(Later_Age_1) + " " + "in three years.")

We can call the function by typing its name and giving it the variable it will act on in parenthesis.

In [28]:
summarize(Response_ID)

Participant 1 is 34 years old, and will be 37 in three years.

In this example we created our own function but there are many already built in functions. 

We have already used a few: *print(), int(), float(), type()*.

Let's use three other examples of built-in functions: *max()*, *min()*, and *round()*.

We can find the maximum value of an integer list with the function *max*.

In [ ]:
max(1, 2, 3)

This function will work with string values too analyzing them in alphabetical order.

In [ ]:
min('a', 'b', 'c')

The built-in function *round()* will round a floating number to the number of decimals of your choosing. 

This specification of how many decimals the function must round up to is called a *parameter*.

Parameters are included in the parenthesis after the function name and are separated by comas:

*function(parameter, parameter)*

To round the floating number 5.389 to 1 decimal, we will do the following:

In [ ]:
round(5.389, 1)

Certain functions are available only for a specific kind of objects (in programming language, a *class* of objects). For example, some functions are available only for strings.

When that is the case, those functions are referred to as *methods* and are called by adding a dot *.* before their name.

For example:

The method *str.upper* is available for strings. It will act on the string they are called upon and change it from lower case to upper case.

To call it, we will write the object_name, a dot, the method name and a parenthesis:

*object_name.method_name()*

In [29]:
first_name = 'sam'
first_name.upper()

'SAM'

This would print out the variable ONCE in capital letters.

What would you do if you wanted it to be printed always from now on in capital letters?

In [30]:
first_name = first_name.upper()
print(first_name)

SAM

This method can be used on any string value, not just variables. For example:

In [31]:
'Sam'.upper()

'SAM'

You can find out what a method does by using the function *help*.

In [32]:
help(str.upper)

Help on method_descriptor:

upper(self, /)
    Return a copy of the string converted to uppercase.

Find our what these other methods do:

*str.replace*

*str.find*

*str.lower*

In [ ]:
help(str.replace)

Great job. Questions so far?



<h1>Lists</h1>

Learning Objectives:
- Grouping  data points: Understand how to create and modify a list, and what a list can and can't do
- Manipulating your groups of data points: Become familiar with common list methods

A list is an ordered, indexable collection of data. Lets say you're doing a study on the following hometowns:

hometown:

"Brooklyn", "Atlanta", "Hampton", "Brentwood", "Lexington"

You could put that data into a list

contain data in square brackets [...],
each value is separated by a comma ,.

In [33]:
Hometown_list = ["Brooklyn", "Atlanta", "Hampton", "Brentwood", "Lexington"]
type(Hometown_list)

list


<h1>Use an item’s index to fetch it from a list.</h1>

- Each value in a list is stored in a particular location.
- Locations are numbered from 0 rather than 1.
- Use the location’s index in square brackets to access the value it contains.

["Brooklyn", "Atlanta", "Hampton", "Brentwood", "Lexington"]

index: 0             1          2          3          4

In [34]:
print('the first item is:', Hometown_list[0])
print('the fourth item is:', Hometown_list[3])

the first item is: Brooklyn
the fourth item is: Brentwood

Lists can be indexed from the back using a negative index.

["Brooklyn", "Atlanta", "Hampton", "Brentwood", "Lexington"]

index: -5 -4 -3 -2 -1

In [35]:
print(Hometown_list[-1])
print(Hometown_list[-2])

Lexington
Brentwood

## "Slice" a list using [ : ]

- Just as with strings, we can get multiple items from a list using slicing
- Note that the first index is included, while the second is excluded

In [36]:
print(Hometown_list[1:4])

['Atlanta', 'Hampton', 'Brentwood']

Leave an index blank to get everything from the beginning / end

In [37]:
print(Hometown_list[:4])

['Brooklyn', 'Atlanta', 'Hampton', 'Brentwood']

In [38]:
print(Hometown_list[2:])

['Hampton', 'Brentwood', 'Lexington']

<h1>Use index in a string</h1>

Following the same principle, you can also use index to fetch for certain letters in a string.

In [40]:
Hometown = "New York"
Hometown[1]

'e'

Lets get the first eight letters

In [41]:
Hometown[0:8]

'New York'

## Lists’ values can be replaced by assigning to specific indices.

In [43]:
Hometown_list[0] = "New York"
print('Hometown List is now:', Hometown_list)

Hometown List is now: ['New York', 'Atlanta', 'Hampton', 'Brentwood', 'Lexington']

- This makes lists different from strings.
- You cannot change the characters in a string after it has been created.
- Immutable: cannot be changed after creation.
- In contrast, lists are mutable: they can be modified in place.

In [45]:
Hometown = "New York"
Hometown[0] = 'C'

TypeError: ignored

## Mutability has consequences.
The fact that lists are mutable also means that any other variables pointing to a list will also changed if that list gets changed:

In [46]:
New_hometown_list = Hometown_list
print("original list: ", Hometown_list)
print("new list: ", New_hometown_list)
print()

Hometown_list[0] = "Hollywood"
print("original list: ", Hometown_list)
print("new list: ", New_hometown_list)

original list:  ['New York', 'Atlanta', 'Hampton', 'Brentwood', 'Lexington']
new list:  ['New York', 'Atlanta', 'Hampton', 'Brentwood', 'Lexington']

original list:  ['Hollywood', 'Atlanta', 'Hampton', 'Brentwood', 'Lexington']
new list:  ['Hollywood', 'Atlanta', 'Hampton', 'Brentwood', 'Lexington']

But it goes both ways! If a variable pointing to that list is changed, then the original list itself is changed.

In [47]:
New_hometown_list[0] = "Pasadena"
print("original list: ", Hometown_list)
print("new list: ", New_hometown_list)

original list:  ['Pasadena', 'Atlanta', 'Hampton', 'Brentwood', 'Lexington']
new list:  ['Pasadena', 'Atlanta', 'Hampton', 'Brentwood', 'Lexington']

## How to avoid mutability? Slicing!
If you want to make a copy of the original list and then make changes without interfering with the original list, slicing can help you to create a copy and the original list is not multable by any changes made in the new copy.

In [49]:
Derived_hometown_list = Hometown_list[:3]
print("first three hometowns:", Derived_hometown_list)

Hometown_list[1] = "Ithaca"
print("changed hometown_list: ", Hometown_list)

print("first three hometowns:", Derived_hometown_list, "...still!")

first three hometowns: ['Pasadena', 'Atlanta', 'Hampton']
changed hometown_list:  ['Pasadena', 'Ithaca', 'Hampton', 'Brentwood', 'Lexington']
first three hometowns: ['Pasadena', 'Atlanta', 'Hampton'] ...still!

Only *country_list* changed! The *derived_list* doesn't change with *country_list*

## Lists have Methods
- Just like strings have methods, lists do too.
- IPython lets us do tab completion after a dot ('.') to see what an object has to offer.

In [ ]:
Hometown_list.

If you want to append items to the end of a list, use the append method.

In [50]:
Hometown_list.append("Seattle")
print(Hometown_list)

['Pasadena', 'Ithaca', 'Hampton', 'Brentwood', 'Lexington', 'Seattle']

## Use del to remove items from a list entirely.
- del list_name[index] removes an item from a list and shortens the list.
- Not a function or a method, but a statement in the language.

In [52]:
print("original list was:", Hometown_list)
del Hometown_list[3]
print("the list is now:", Hometown_list)

original list was: ['Pasadena', 'Ithaca', 'Hampton', 'Lexington', 'Seattle']
the list is now: ['Pasadena', 'Ithaca', 'Hampton', 'Seattle']

## Challenge 1: Slice It

In [ ]:
thing = [1,3,8,20,6, 'Kentwood', 'Washington', 200, 2, 'Tulsa']
low = 2
high = 8
thing[:8]

- What does thing[low:high] do?
- What does thing[low:] (without a value after the colon) do?
- What does thing[:high] (without a value before the colon) do?
- What does thing[:] (just a colon) do?

## Challenge 2: Index
I've created a (long) list for you below. Use the .index() method to find out what the index number is for Waldo

In [ ]:
Wheres_Waldo = ["Anna", "Shad", "Rachel", "Maura", "Jason", "Matt", "Konrad", "Justine", "Sarah", "Laura", \
                "Chelsea", "Nina", "Dierdre", "Julian", "Waldo", "Naniette", "Melissa", "Biz", "Elsa", "Demetria",\
                "Liz", "Olivia", "Will", "Ogi", "Melanie", "Jessica"]
print(Wheres_Waldo.index("Olivia"))
print(Wheres_Waldo.index("Waldo"))

## Challenge 3: Join
Read the help file (or the Python documentation) for join(), a string method.

In [ ]:
str.join?

Using the join method, concatenate all the values in this list into one string:

In [55]:
letters = ['N', 'a', 's', 'h', 'v', 'i', 'l', 'l', 'e']

In [56]:
''.join(letters)

'Nashville'

Great Job! Next, we will look into Loops and Conditions.

# Loops and Conditions
Time

Teaching: 10 min
Exercises: 15 min

Learning Objectives:

- Explain what loops are normally used for.
- Trace the execution of a simple (unnested) loop and correctly state the values of variables in each iteration.
- Write for loops that use the Accumulator pattern to aggregate values.

## A for loop executes commands once for each value in a collection.

print three hometowns: Atlanta, Kentwood, Cincinnatti

In [58]:
print('Atlanta')
print('Kentwood')
print('Cincinnatti')

Atlanta
Kentwood
Cincinnatti

for each thing in this group, do these operations

In [60]:
for hometown in ['Atlanta', 'Kentwood', 'Cincinnatti']:
    print(hometown)

Atlanta
Kentwood
Cincinnatti

## The first line of the for loop must end with a colon, and the body must be indented.
- The colon at the end of the first line signals the start of a block of statements.
- Python uses indentation rather than {} or begin/end to show nesting.
- Any consistent indentation is legal, but almost everyone uses four spaces.

## A for loop is made up of a collection, a loop variable, and a body.

In [ ]:
for hometown in ['Atlanta', 'Kentwood', 'Cincinnatti']:
    print(hometown)

Atlanta
Kentwood
Cincinnatti

- The collection, ['Atlanta', 'Kentwood', 'Cincinnatti'], is what the loop is being run on.
- The body, print(hometown), specifies what to do for each value in the collection.
- The loop variable, hometown, is what changes for each iteration of the loop, the "current thing".

## The Accumulator pattern turns many values into one.
- A common pattern in programs is to:
 - Initialize an accumulator variable to zero, the empty string, or the empty list.
 - Update the variable with values from a collection.

If only one argument is given to range, the minimum will default to 0. But two arguments may also be given:

In [61]:
ages = [18, 21, 34, 40, 18, 19, 20]

later_ages = []
for age in ages:
    later_ages.append(age+3)

print(later_ages)

[21, 24, 37, 43, 21, 22, 23]

## Challenge 1: Square roots
Fill in the blanks in the program below so that it prints the square root for each number in squares. You can get the square root of a number like this:

number ** .5

In [ ]:
squares = [1, 4, 9, 16, 25]

for x in squares:
    print(x ** 0.5)

1.0
2.0
3.0
4.0
5.0

# Conditionals
Learning Objectives:

- Being more specific with your data: 

  * Correctly write programs that use if and else statements and simple Boolean expressions (without logical operators).
  * Trace the execution of unnested conditionals and conditionals inside loops.

Keypoints:
 - Use if statements to control whether or not a block of code is executed.
 - Conditionals are often used inside loops.
 - Use else to execute a block of code when an if condition is not true.
 - Use elif to specify additional tests.
 - Conditions are tested once, in order.

## Use if statements to control whether or not a block of code is executed.
- An if statement (more properly called a conditional statement) controls whether some block of code is executed or not.
- Structure is similar to a for statement:
 - First line opens with if, contains a Boolean variable or expression, and ends with a colon
 - Body containing one or more statements is indented (usually by 4 spaces)

In [66]:
age_1 = 23
if age > 21
    print('Being ' + str(age_1) + ', participant 1 is of age.')

Being 21, participant 1 is of age.

In [69]:
age_2 = 18
if age_2 < 21:
    print ('Being ' + str(age_2) + ', participant 2 is under age.')

Being 18, participant 2 is under age.

# Conditionals are often used inside loops.
- Not much point using a conditional when we know the value (as above).
- But useful when we have a collection to process.

In [71]:
#pick out under age

ages = [21, 19, 18, 21, 20]
for age in ages:
    if age < 21:
        print(age, 'is in under age group')

19 is in under age group
18 is in under age group
20 is in under age group

## Use else to execute a block of code when an if condition is not true.
- else is always attached to if.
- Allows us to specify an alternative to execute when the if branch isn't taken.

In [72]:
ages = [21, 19, 18, 21, 20]
for age in ages:
    if age < 21:
        print(age, 'is in under age group')
    else:
        print(age, 'is not in under age group')

21 is not in under age group
19 is in under age group
18 is in under age group
21 is not in under age group
20 is in under age group

# Use elif to specify additional tests.
- May want to provide several alternative choices, each with its own test.
- Use elif (short for "else if") and a condition to specify these.
- Always associated with an if.
- Must come before the else (which is the "catch all").

In [76]:
ages = [18, 88, 23, 97, 34]
for age in ages:
    if age > 65:
        print(age, 'is in elders group')
    elif age > 21:
        print(age, 'is in adult group')
    else:
        print(age, 'is in teenagers group')

18 is in teenagers group
88 is in elders group
23 is in adult group
97 is in elders group
34 is in adult group

## Challenge 1: Recoding the variable
Fill in the blanks so that this program creates a new list containing lables, "young", "middle", "elder", to indicate the age group.

In [79]:
ages = [18, 88, 23, 97, 34]
result = []
for age in ages:
    if age > 65:
        result.append('elder')
    elif age > 21:
        result.append('adult')
    else:
        result.append('teeanger')
print(result)

['teeanger', 'elder', 'adult', 'elder', 'adult']

# Challenge 2: String Conditionals
Here are our presidents. Let's pick out last names starting with B.

To grab the last name, you can use the split method to seperate a string into a list of strings based on spaces. Here is an example:

In [80]:
president="Franklin D. Roosevelt"
name_split=president.split()
print(name_split)

['Franklin', 'D.', 'Roosevelt']

In [ ]:
presidents_full = ["George Washington", "John Adams", "Thomas Jefferson", "James Madison", "James Monroe", \
        "John Quincy Adams", "Andrew Jackson", "Martin Van Buren", "William Henry Harrison", "John Tyler", \
        "James K. Polk", "Zachary Taylor", "Millard Fillmore", "Franklin Pierce", "James Buchanan", \
        "Abraham Lincoln", "Andrew Johnson", "Ulysses S. Grant", "Rutherford B. Hayes", "James A. Garfield", \
        "Chester A. Arthur", "Grover Cleveland", "Benjamin Harrison", "Grover Cleveland", "William McKinley", \
        "Theodore Roosevelt", "William Howard Taft", "Woodrow Wilson", "Warren G. Harding", "Calvin Coolidge", \
        "Herbert Hoover", "Franklin D. Roosevelt", "Harry S. Truman", "Dwight D. Eisenhower", "John F. Kennedy", \
        "Lyndon B. Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter", "Ronald Reagan", "George H. W. Bush", \
        "Bill Clinton", "George W. Bush", "Barack Obama"]

result = []
for president in presidents_full:
    name_split=president.split()
    #print(name_split)
    last_name= name_split[-1] 
    start_letter= last_name[0] 
    if start_letter == "B":
        result.append(last_name)
        print(president)
    else:
        result.append('no')
print(result)

Martin Van Buren
James Buchanan
George H. W. Bush
George W. Bush
['no', 'no', 'no', 'no', 'no', 'no', 'no', 'Buren', 'no', 'no', 'no', 'no', 'no', 'no', 'Buchanan', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'Bush', 'no', 'Bush', 'no']